name: "DECAF Webapps Deployment"
description: "Deploys DECAF Web Apps"
author: "Teloscube Pte Ltd"
branding:
  icon: "arrow-up-right"
  color: "orange"
inputs:
  app_name:
    description: "Name of the application and also the folder name where the application is located remotely"
    required: true
  production:
    description: "Production environment"
    required: false
  staging:
    description: "Staging environment"
    required: false
  preview:
    description: "Deployment from Pull Request"
    required: false
  version:
    description: "Deployment from a tag or version"
    required: false
  deployment_domain:
    description: "Domain of the app URL. Default is sandbox.dev.decafhub.com"
    required: false
    default: "sandbox.dev.decafhub.com"
  remote_host:
    description: "The remote host"
    required: true
  remote_user:
    description: "The remote user"
    required: true
  remote_key:
    description: "The remote key"
    required: true
  remote_port:
    description: "The remote port"
    required: false
    default: 22
  sentry_org:
    description: "The sentry organization"
    required: false
  sentry_project:
    description: "The sentry project"
    required: false
  sentry_token:
    description: "The sentry token to upload the sourcemaps"
    required: false
  build_folder:
    description: "The build folder"
    required: false
    default: "build"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install rsync
      id: install_rsync
      run: sudo apt-get install -y rsync
      shell: bash

    - name: Build and Deploy
      id: build
      run: ${{ github.action_path }}/run-build-and-deploy.sh
      shell: bash
      env:
        INPUT_APP_NAME: ${{ inputs.app_name }}
        INPUT_PRODUCTION: ${{ inputs.production }}
        INPUT_STAGING: ${{ inputs.staging }}
        INPUT_PREVIEW: ${{ inputs.preview }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_REMOTE_HOST: ${{ inputs.remote_host }}
        INPUT_REMOTE_USER: ${{ inputs.remote_user }}
        INPUT_REMOTE_PORT: ${{ inputs.remote_port }}
        INPUT_REMOTE_KEY: ${{ inputs.remote_key }}
        INPUT_SENTRY_ORG: ${{ inputs.sentry_org }}
        INPUT_SENTRY_PROJECT: ${{ inputs.sentry_project }}
        INPUT_SENTRY_TOKEN: ${{ inputs.sentry_token }}
        INPUT_BUILD_FOLDER: ${{ inputs.build_folder }}

    - name: "Comment on PR"
      uses: actions/github-script@v6
      env:
        DEPLOY_URLS: ${{steps.build.outputs.urlpaths}}
        APP_DOMAIN: ${{ inputs.deployment_domain }}
      if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened') }}
      with:
        script: |
          const {
            issue: { number: issue_number },
            repo: { owner, repo },
          } = context;
          process.env.DEPLOY_URLS.split('||').forEach(path => {
            github.rest.issues.createComment({ issue_number, owner, repo, body: `🚀  Deploy Preview: https://${process.env.APP_DOMAIN}${path}` });
          });
